[UART - Driver] Added basic USART driver
MateuszMyalski/stm32_iot_hal pull request #22
Opened 2022-03-25 23:47 UTC by bgs94

Dunno how to set the review on gerrithub yet. Regarding the commit, following assumptions were made:
- rx and tx pins are on the same share same io port,
- usart configures rx and tx  lines by it's own as agreed recently (every peripheral should handle related io via peripheral_ioctl)
Also added sample bsp_ioctl api to configure signals available on connectors.

2022-03-27 12:39 UTC, bgs94 commented
As we agreed today, I will move the initialization functionality to `hal_usart_open()`. Feeding clock to the peripheral will be moved out of current open() to `ll_usart_enable_apb()`.

2022-03-27 15:13 UTC, MateuszMyalski commented on sdk/bsp/inc/bsp.h
> +#define BSP_USART1_TX_PIN  9u
NIT: Please align lowercase u/ul to capital letters L/UL

2022-03-27 15:13 UTC, MateuszMyalski commented on sdk/bsp/inc/bsp.h
> +    BSP_PMOD     /* CN4-PMOD connector */
Can we also add other connector to the enum list?

2022-03-27 15:14 UTC, MateuszMyalski commented on sdk/bsp/src/periphs.c
> +
Please remove empty line

2022-03-27 15:15 UTC, MateuszMyalski commented on sdk/bsp/src/periphs.c
> +hal_err_t bsp_ioctl(BSP_connector connector, BSP_periph_sel peripheral) {
Maybe do not mix error codes. hal_err_t  should be used only in hal level. Current, the standard for bsp is just return int. We can agree to leave it as int or create it's own error code.

2022-03-27 15:17 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/inc/hal_usart.h
> +#define USART_DEFAULT_KCLK_SPEED  16000000U
what 'K' stands for in KCLK? It is rather UL (Unsigned long)

2022-03-27 15:21 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +
Remove first empty line

2022-03-27 15:22 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +static uint32_t usart_kernel_clk = USART_DEFAULT_KCLK_SPEED;
Seems unused?

2022-03-27 15:24 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +    hal_gpio_ioctl(io_port, rx_pin, gpio_ioctl_push_pull);
Pin setup should not be done in the ioctl. Ioctl suppose to configure the peripheral attributes such baudrate, stopbits etc.

2022-03-27 15:25 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +void hal_usart_open(USART_TypeDef *USART) {
Here the user should decide the mode of usart (basic setup of ioctl)

2022-03-27 15:26 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +hal_err_t hal_usart_init(USART_TypeDef *USART, USART_baud baud, GPIO_TypeDef *io_port, uint32_t tx_pin, uint32_t rx_pin) {
As discussed, please reorganize

2022-03-27 15:27 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +            break;
Shoudl return error

2022-03-27 15:29 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +int hal_usart_tx(USART_TypeDef *USART, uint8_t *tx_buffer, uint8_t nbytes) {
Change type for nbytes to size_t

2022-03-27 15:30 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        while (!is_usart_tx_empty(USART)) {
is_usart_tx_empty -> ll_is_usart_tx_empty

2022-03-27 15:30 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        while (!is_usart_tx_empty(USART)) {
Or maybe event bind it into one ll function, as in i2c?

2022-03-27 15:31 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +    while (!is_usart_tx_complete(USART)) {
Is it really needed?

2022-03-27 15:32 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +            if (is_usart_rx_timeout(USART)) {
The timeout should be configured via ioctl. The user can have need to block till first char

2022-03-27 15:33 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/LL/inc/ll_common.h
> +#include <stdbool.h>
Maybe drop this as discussed offline

2022-03-27 15:34 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/LL/inc/ll_usart.h
> +    return (USART->ISR & USART_ISR_TXE_TXFNF) ? true : false;
Use READ_BIT same below

2022-03-27 15:36 UTC, MateuszMyalski requested changes
Please resolve comments

2022-03-28 19:33 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/inc/hal_usart.h
> +#define USART_DEFAULT_KCLK_SPEED  16000000U
pclk - peripheral clock,
kclk - kernel clock (not the OS one)

Some of peripherals (if not the majority) can be clocked independently from two sources or just from peripheral clock. What is the advantage you may ask? Well.. I believe it has positive impact on flexibility and power consumption features but I did not spent too much time on analysis. Just thought it might be useful to distinguish two sources just from the begining.

2022-03-28 19:33 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +
Done.

2022-03-28 19:33 UTC, bgs94 commented on sdk/bsp/src/periphs.c
> +
Done.

2022-03-28 19:35 UTC, bgs94 commented on sdk/bsp/inc/bsp.h
> +    BSP_PMOD     /* CN4-PMOD connector */
Sure we can, but for now I did not put another stuff there. If you think this is a good idea to have connectors enumerated, let;s just keep it as it is for now and expand the list when there is a need :)

2022-03-28 19:37 UTC, bgs94 commented on sdk/bsp/src/periphs.c
> +hal_err_t bsp_ioctl(BSP_connector connector, BSP_periph_sel peripheral) {
Agreed. Let the 'bsp' return an integers for now and we will decide what to do about it in the future.

2022-03-28 19:47 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +static uint32_t usart_kernel_clk = USART_DEFAULT_KCLK_SPEED;
Yes, despite the compiler does not complain about it, the variable is redundant considering current implementation. It will become usefull in the future if we decide to clock the usart kernel domain from different source than the peripheral clock.

2022-03-28 19:49 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +            break;
Done.

2022-03-28 19:51 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +int hal_usart_tx(USART_TypeDef *USART, uint8_t *tx_buffer, uint8_t nbytes) {
Done, same for rx.

2022-03-28 19:58 UTC, bgs94 commented on sdk/hal-drivers/peripherals/LL/inc/ll_usart.h
> +    return (USART->ISR & USART_ISR_TXE_TXFNF) ? true : false;
Done.

2022-03-28 20:15 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        while (!is_usart_tx_empty(USART)) {
ll_is_usart_tx_empty aaaand this is the monstrosity I wanted to avoid :) What do you mean about the binding? Putting whole line (93) into a function that would just wait for tx buffer to be empty?

2022-03-28 20:26 UTC, bgs94 commented on sdk/bsp/inc/bsp.h
> +#define BSP_USART1_TX_PIN  9u
Done.

2022-03-28 20:53 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +    while (!is_usart_tx_complete(USART)) {
Currently - not really, but as the reference manual says: _This check is required to avoid corrupting the last transmission when the USART is disabled or enters Halt mode._ Therefore I decided to put this check here, just in case. I think there is rather small chance of having flow like `usart_tx()` and in nex line `usart_disable()`, but who knows. I think we can leave it here.

2022-03-30 18:21 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/LL/inc/ll_common.h
> +#include <stdbool.h>
Agree. As discussed offline, you can start some desing doc on confluence to align styli in hal an ll layers.

2022-03-30 18:27 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        while (!is_usart_tx_empty(USART)) {
I mean binding tx_write and is_usart_tx_empty to usart_send byte as ll_i2c_send_byte

2022-03-30 18:35 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +    while (!is_usart_tx_complete(USART)) {
If the datasheet says so I will not discuss with it! Good practice to read carefully documents! I would suggest to maybe add a comment with comment and datasheet page where the procedure is then highlight each step as the documents describe it. Thoughts?

2022-03-31 18:56 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        while (!is_usart_tx_empty(USART)) {
done

2022-03-31 18:57 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +    while (!is_usart_tx_complete(USART)) {
Done :)

2022-03-31 19:15 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +            if (is_usart_rx_timeout(USART)) {
I think type of timeout has a different nature than the one you have on your mind as it operates on the peripheral level. Here is what datasheet says (**RM0465 57.5.17 USART receiver timeout**):

_"The receiver timeout counter starts counting:
• from the end of the stop bit if STOP = 00 or STOP = 11
• from the end of the second stop bit if STOP = 10.
• from the beginning of the stop bit if STOP = 01."_

This means that the receiver timeout is calculated **after** the data has been recevied, therefore it cannot be used to block on read operation. Nevertheless, blockiing read can be useful and deserves implementation, especially a thread-safe one ;)

2022-04-06 19:59 UTC, merged