20 usart logger
MateuszMyalski/stm32_iot_hal pull request #30
Opened 2022-04-08 23:35 UTC by bgs94

- added new api to usart hal: hal_usart_putchar which is used in syscalls,
- added new api to set usart instance for standard i/o,
- PMOD signals are now configured in bsp_init()
- tested - logger is working

2022-04-10 08:04 UTC, MateuszMyalski requested changes
Good work! Please resolve comments and we are ready to merge :) 
![image](https://user-images.githubusercontent.com/59411812/162608750-0e12a25a-da19-4573-81b9-46e0fbeea708.png)

2022-04-10 08:04 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        asm("nop");
Such NOPs are redundant. Compiler will optimize it in higher -O flags. Further more this NOP is adding unnecessary clock delay before exiting the wait loop. 

https://godbolt.org/z/aK9oqqYGh

Here, please notice, that after reaching the desired flag value NOP version of the while is delaying unnecessary the program flow by additional clock cycle. Blocking the program with “while” should be as fast as possible to exit in case of positional value.

2022-04-10 08:04 UTC, MateuszMyalski commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        asm("nop");
In case your agreement pleace align to other waits

2022-04-10 08:11 UTC, MateuszMyalski commented on app/appMFG/src/syscalls.c
> +    if(NULL == stdio_usart_instsnce) {
I am also wondering. Can you make such test? What if you use _Static_assert in write handler. Can you check please, if in compile time, it will find out that the pointer is NULL?

2022-04-10 09:53 UTC, bgs94 commented on sdk/hal-drivers/peripherals/HAL/src/hal_usart.c
> +        asm("nop");
Thanks for good explanation again. This time I sholud remeber it. I agree to remove "nop's" from usart API

2022-04-10 10:57 UTC, bgs94 commented on app/appMFG/src/syscalls.c
> +    if(NULL == stdio_usart_instsnce) {
Excellent idea, I will try it!

2022-04-11 14:25 UTC, MateuszMyalski commented
One more thought. I think you should also implement getchar syscall

2022-04-11 19:36 UTC, bgs94 commented
I have missed the part about getchar but.. we can merge this branch for now and I will add getchar together with CLI implementation. What do you think?

2022-04-11 19:37 UTC, merged